feat(docs): fix grammer issues in README.md
n25a/gorabbit pull request #1
Opened 2023-12-09 07:53 UTC by rsharifnasab

2023-12-11 08:24 UTC, n25a requested changes

2023-12-11 08:24 UTC, n25a commented on README.md
> -It's good to mentioned that gorabbit handles the reconnection and reconsuming the jobs automatically.
the orginal text is correct. gorabit handle reconsuming that very important feature.

2023-12-11 08:36 UTC, rsharifnasab commented
You are right. Reverted that specific change.

2023-12-12 20:32 UTC, n25a approved these changes

2023-12-12 20:33 UTC, merged

2023-12-12 20:34 UTC, n25a commented
Thanks for your contribution. ☕